wip

diff --git a/transfer b/transfer
--- a/transfer
+++ b/transfer
@@ -17,7 +17,7 @@ display_usage() {
   echo "          the full rsync command and terminate without doing anything"
 }
 
-# if there are no arguments
+# if there are no arguments, display usage and exit
 if [ $# -eq 0 ]
 then
   echo ""
@@ -28,7 +28,14 @@ fi
 
 # Reset OPTIND in case getopts has been used previously in the shell.
 OPTIND=1
-rules_file="OUTPUT"
+
+# a file to hold the output of commands
+output_file="OUTPUT"
+
+# a file to hold the edited rules
+rules_file="RULES"
+
+# argument flag values
 download=0
 upload=0
 force=0
@@ -139,11 +146,14 @@ then
   exit 1
 fi
 
-# intialize has_rules to 0 and then check for rules
-has_rules=0
+# -a rsync option is always present
 rsync_command="`which rsync` -a"
 
+# intialize has_rules to 0 and then check for rules
+has_rules=0
+
 rm $rules_file
+
 # parse the rules
 while read line; do
   first_char=${line:0:1}
@@ -152,6 +162,7 @@ while read line; do
     has_rules=1
     echo "$line" >> $rules_file
   fi
+  
   if [[ "$first_char" == "-" ]]
   then
     has_rules=1
@@ -194,7 +205,7 @@ fi
 # if -t (testing) is present, do nothing. dump the rsync command and dump the rules file
 if [[ $testing -eq 1 ]]
 then
-  rsync_options="$rsync_options -nv"
+  rsync_options="$rsync_options -nv" # -nv for dry run
   echo "$rsync_command $rsync_options $srcdst"
   cat $rules_file
   exit 0
@@ -202,30 +213,50 @@ fi
 
 dry_run_options="$rsync_options -nv"
 echo "$rsync_command $dry_run_options $srcdst"
-rm  "dry_run_output"
+rm "dry_run_output"
 $rsync_command $dry_run_options $srcdst > "dry_run_output"
 
-count=0
-while read line; do
- ((++count))
-done < "dry_run_output"
+#cat /dev/null > $dry_run_output
 
-line_number=0
-interesting_lines=()
-while read line; do
- minus_one=$((count-1))
- minus_two=$((count-2))
- minus_three=$((count-3))
- if [ ! $line_number -eq 0 ] && [ ! $line_number -eq $minus_one ] && [ ! $line_number -eq $minus_two ] && [ ! $line_number -eq $minus_three ]
- then
-   interesting_lines+=($line)
-   echo $line
- fi
- ((++line_number))
-done < "dry_run_output"
-echo interesting_lines[0]
-echo interesting_lines[1]
+#echo "$(<dry_run_output)"
+
+#awk 'NF' $rules_file
+#cat /dev/null > file.txt
+
+#cat $dry_run_output
+# count=0
+# while read line; do
+#  ((++count))
+# done < "dry_run_output"
+#
+# line_number=0
+# interesting_lines=()
+# while read line; do
+#  minus_one=$((count-1))
+#  minus_two=$((count-2))
+#  minus_three=$((count-3))
+#  if [ ! $line_number -eq 0 ] && [ ! $line_number -eq $minus_one ] && [ ! $line_number -eq $minus_two ] && [ ! $line_number -eq $minus_three ]
+#  then
+#    interesting_lines+=($line)
+#    echo $line
+#  fi
+#  ((++line_number))
+# done < "dry_run_output"
+#echo interesting_lines[0]
+#echo interesting_lines[1]
 
 $rsync_command $rsync_options $srcdst
 
+# when SIGINT is revieved (Ctrl-C in shell), call cleanup
+trap "cleanup" INT
+
+# cleanup function
+cleanup() {
+	rm -f $output_file
+	rm -f $rules_file
+	exit
+}
+
+# remove temporary output and rules file upon completion of the script
+#cleanup
 
